# Generated by Django 4.1.4 on 2022-12-14 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PatientInfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("patientName", models.CharField(max_length=25, unique=True)),
                ("patientPassword", models.CharField(max_length=25)),
                ("secret_key", models.CharField(max_length=25)),
                ("purpose", models.CharField(max_length=500)),
                ("doctorName", models.CharField(max_length=254)),
                ("patientHward", models.CharField(max_length=25)),
                ("Date_of_Birth", models.DateField()),
                (
                    "Gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=150
                    ),
                ),
                ("Marital_status", models.CharField(max_length=50)),
                (
                    "Blood_Group",
                    models.CharField(
                        choices=[
                            ("POSITIVE", "A+"),
                            ("NEGATIVE", "A-"),
                            ("POSITIVE", "B+"),
                            ("NEGATIVE", "B-"),
                            ("POSITIVE", "O+"),
                            ("NEGATIVE", "O-"),
                            ("POSITIVE", "AB+"),
                            ("NEGATIVE", "AB-"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "Genotype",
                    models.CharField(
                        choices=[
                            ("M", "AA"),
                            ("F", "AS"),
                            ("M", "AC"),
                            ("Z", "SS"),
                            ("G", "SC"),
                        ],
                        max_length=30,
                    ),
                ),
                ("Phone_no", models.IntegerField()),
                ("Illness", models.CharField(max_length=250)),
                ("Medical_history", models.TextField()),
                ("Resident_Address", models.CharField(max_length=300)),
                ("Allegies", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Pharmacy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Drug_name", models.CharField(max_length=300)),
                ("Cost", models.CharField(max_length=300)),
                ("Category", models.CharField(max_length=300)),
                ("Selling_price", models.CharField(max_length=300)),
                ("Qty", models.CharField(max_length=300)),
                ("Man_date", models.DateField()),
                ("Exp_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="StaffInfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uid", models.TextField(max_length=25)),
                ("username", models.TextField(max_length=254)),
                ("password", models.TextField(max_length=25)),
                ("role", models.TextField(max_length=50)),
                ("certification", models.TextField(max_length=25)),
                ("specialization", models.TextField(max_length=50)),
                ("hward", models.TextField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Laboratory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result", models.CharField(max_length=300)),
                ("sample_type", models.CharField(max_length=300)),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ehr.patientinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Consultant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Lab_test", models.CharField(max_length=300)),
                ("Doctor_diagnostic", models.CharField(max_length=300)),
                ("Doctor_Observation", models.CharField(max_length=300)),
                ("Medication", models.CharField(max_length=300)),
                ("Recommendation", models.CharField(max_length=300)),
                ("Doctor", models.CharField(max_length=300)),
                ("visit_time", models.CharField(max_length=300)),
                ("result", models.CharField(max_length=300)),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ehr.patientinfo",
                    ),
                ),
            ],
        ),
    ]
