# Generated by Django 4.1.4 on 2022-12-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ehr", "0002_alter_patientinfo_patientpassword"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientinfo",
            name="Blood_Group",
            field=models.CharField(
                choices=[
                    ("A", "A+"),
                    ("A", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="Genotype",
            field=models.CharField(
                choices=[
                    ("AA", "AA"),
                    ("AS", "AS"),
                    ("AC", "AC"),
                    ("SS", "SS"),
                    ("G", "SC"),
                ],
                max_length=30,
            ),
        ),
    ]
